# Welcome to PowerTools PowerTools.config!!
# You can use this plugin addons in this file!

# Enable this if you using bungeecord
# Plugin will sync with bungeecord...
bungeecord: false

Discord:
  WebHook:
    enabled: false
    url: ""
  Bot:
    token: ""

Extensions:
  - DiscordLink
  - PlayerManager
  - CommandPanel
  - Profiles

ChatManager:
  enabled: false
  AntiSpam:
    enabled: true
    maxSpam: 2 # if player spam 3 times will kick!
    filterSplitters: true
    Kick:
      enabled: true
  WordBlock:
    enabled: true
    Words: [ "fuck", "bitch", "fvck" ]
    Modes:
      UniCodes: true
      Splitters: true
      MultiLetter: true
  AntiDuplicate:
    enabled: true
    maxDuplicate: 2
  MessageDelay:
    enabled: true
    delay: 2
  PlayerMentions:
    enabled: false
    Mode: "title" # ["title", "chat", "both"]
  CommandCooldown:
    enabled: true
    delay: 1 # 1 Second command cooldown
  AntiAdventure: # Prevent players from sending links
    enabled: true

NetworkChecker: # This plugin uses an api that only render 45 requests per minute ( sometimes this addon may don't check players )
  enabled: false
  CountriesList:
    # You can insert 'blacklist' or 'whitelist'
    type: "blacklist"
    list:
      - US
  blackListedIPs:
    - 127.0.0.1

AntiBot:
  enabled: false
  FastJoin:
    enabled: false
    maxJoinPerSecond: 25
  UserNameLearning:
    enabled: true
  MultiIP:
    enabled: true
  PingAttack:
    enabled: true
    maxPingPerSecond: 85

UsernameManager:
  enabled: false
  alert-on-discord: false
  WordBlock:
    enabled: true
    Words: [ "fuck", "fvck", "bitch" ]
    Modes:
      Splitters: true
      MultiLetter: true
    Action: "BAN" # You can insert [KICK, BAN] items in string
    msg: "&cBad name"

Captcha:
  enabled: false
  # AIs:
  # Map: Give player a map... in map we can see number... player most write the number in chat
  # GUI: Open a gui with random items... player most select the one has "This One" text
  # GUI-AB: Open a gui with random items... player most select the one has "So One" text ( Anti-Bypass ) ( NOTE: TenaCity ( hacked client ) can't render its text )
  AI: "GUI"
  MapsLink:
    "1234": https://test.net/examplePic/1234.png
    "532a": https://test.net/examplePic/532a.png

CpsCheck:
  enabled: false
  maxCps:
    RMB:
      enabled: true
      alert-on-discord: false
      max: 40
    LMB:
      enabled: true
      alert-on-discord: false
      max: 35
  AutoClickerCheck:
    enabled: true
    clickerRange: 1
    alert-on-discord: true
    startCheck:
      RMB: 15
      LMB: 15

ForceSpawn:
  enabled: false
  world: "world"
  location:
    x: 100
    y: 100
    z: 100
  head:
    yaw: 0
    pitch: 90

Kits:
  enabled: false

JoinMessage:
  enabled: false
  messages:
    # Insert %NAME% for player userName
    # Insert %NUM% for what players join before
    # Insert %ONLINE% for amount of onlinePlayers on server
    FirstJoin: "&6Welcome %NAME% to {serverName}! #%NUM%"
    NotFirstJoin: "&6[&a+&6]&a%NAME%"

QuitMessage:
  enabled: false
    # Insert %NAME% for player userName
  # Insert %ONLINE% for amount of onlinePlayers on server
  message: "&6[&c-&6]&a%NAME%"

afkCheck:
  enabled: false
  kickOnAFK: true
  maxDelayNoAction: 300000 # 300000 MiliSec = 300 Sec = 5 Min
  alert-on-discord: true
  Actions:
    Chat: true
    CommandExecute: true
    Interact: true
    Move: true
    ChangeHeadVictor: true
  notification:
    chat:
      enabled: true
      AFKmessage: "&8* %NAME% is now afk"
      NotAFKmessage: "&8* %NAME% is no longer afk"
    tab:
      enabled: false
      tag: " &cAFK"

CommandDeny:
  enabled: false
  commands: [ "?", "help", "pl", "plugins", "rl", "reload", "version", "timings", "about", "ver", "bukkit" ]
  alert-on-discord: false
  denyPluginNameOnStart: true # like /help OR /bukkit:help
  ignoreOps: true

VersionCheck:
  enabled: false

AntiWorldDownLoader: # Anti WDL
  enabled: false
  continueOperators: false
  alert-on-discord: true

PingCheck:
  enabled: false
  maxPing: 1000
  alert-on-discord: false

pvpManager:
  enabled: false

ChatFormat:
  enabled: false
  format: "&6<&7%player-name%&6> &8message"

DistanceChat:
  enabled: false
  maxDistance: 70

# -->> Note: This option may create lag in public servers ( +10 players )
PvpRegisterer: # Required 100mg/1cps
  enabled: false
  registerDamages: true
  registerKnockback: true
  chance: 85 # 85% / 100%

CommandRedirect:
  enabled: false
  commands:
    "land smp": "smp"
    "land bw": "bw"
    "rl": "reload"

Report:
  enabled: false
  delayBetweenReports: 600000 # 600000 miliSeconds = 600 Seconds = 10 Minutes
  reportTheySelf: false

SlashServer:
  enabled: false
  servers:
    #  ServerName - command
    survival: [ "survival" ]
    bedwars: [ "bw" ]
    pvp: [ "pvp" ]


SurvivalAddOns:
  enabled: false
  NoRespawn: # BETA #When player kill by another player a head will drop from dead player! If that head place, player will respawn... else they're spectator
    enabled: false

  ChatGame:
    # Delays are in InGameTicks: 20 ticks = 1 second: 1200 ticks = 1 minute
    enabled: false
    delay: 18000 # = every 15 mins
    rewardsPerGame: 1 # AI only select 1 reward per game
    answerTime: 1200 # 1 min insert -1 for disable
    rewards:
      Money: 10000 # 10000$ REQUIRED *VAULT ECONOMY*
      IRON_BLOCK: 1
      GOLD_BLOCK: 1
      EMERALD_BLOCK: 1
      DIAMOND: 3

  RandomSpawn:
    enabled: false

  FallingBlocks:
    enabled: false
    doNotApplyOn: # be-careful about what you insert here
      - WATER
      - LAVA
    nullBlocks:
      - AIR
      - GRASS

BedwarsAddOns:
  enabled: false
  AntiTeamup:
    enabled: false
    distance: 5
    maxVL: 20

  TntKnockback:
    enabled: false
    multiply: 1.6

  FireballKnockback:
    enabled: false
    multiply: 1.4

HubAddOns:
  enabled: false
  KnockbackPlates:
    enabled: false
    locations:
      001:
        world: "World" # Insert world's NAME
        location: [ 100, 100 ] #NOTE: [X, Z]
        mode: "HEAD" # Insert "HEAD" to knockback to head direction or "FORCE" to knockback to a default location
        knockback: [ 1, 2, 1 ] # this only work when on FORCE
        multiply: 2 # this only work when on HEAD
        verticalNormal: 2

  VoidTP:
    enabled: false
    respawnLocation:
      x: 100
      y: 100
      z: 100
    teleportY: -5 # When player's Y position get lower than this value will teleport to the respawnLocation

ServerAddOns:
  enabled: false
  randomMOTD:
    enabled: false
    MOTDs:
      - "&6THIS IS MY SERVER!"
      - "&6ANOTHER &5SPIGOT SERVER"

  ForcePing:
    enabled: false
    maxDelay: 5000

  AntiRejoin: # Works better if ForcePing enabled
    enabled: false
    wait: 5000

  BanMOTD:
    enabled: false
    MOTD: "&cYou're Banned from mc.example.net"

  PluginHider:
    enabled: false
    tabComplete: true # This mode will *not* fully block the tab complete!
    disableCommand: true # This mode will disable commands '/pl' & '/plugins'
    chatMessagesCheck: true # This mode will block any message from server to player that contains a plugin name ( note: Will ignore prefixes ) ( only for normal-players )

  # usage will `$$execute {command}` for discord -> minecraft
  # Before enable this you must fill the field: Discord.Bot.token - It's on top of this page
  SyncDiscord:
    enabled: false
    allowedChannelIDs:
      - 44465415418452 # This ID is random
    fromDiscord: true # execute the commands they send in chat at discord

  ConsoleMessageDeny:
    enabled: false
    messages: # Message will filter one of the texts below contains in it
      - "test1 message deny..."
      - "test2 message deny..."
      - "test3 message deny..."
      - "test4 message deny..."

  # Note: Required BungeeCord server & Required the plugin installed on all servers ( they connected to bungeecord ) & this option enabled on all of them ( if disabled on a server that server's chat will private )
  PublicChat:
    enabled: false

  NoUUIDSpoof: # Only works in online-mode servers ( not cracked server )
    enabled: false

RenderAddOns:
  enabled: false
  ScoreBoards:
    enabled: false
    switchDelay: 20 # 20 ticks = 1 second
    name: "Minecraft server"
    boards:
      index01:
        - "&2Welcome to minecraft server"
        - "&2On %onlines-size%/%max-onlines-size%"
        - "&2You're using %cl-brand%"
      index02:
        - "&2Welcome to minecraft server"
        - "&2On %onlines-size%/%max-onlines-size%"
        - "&2You're using %cl-version%"
    # You can insert more items than these
  TabList:
    enabled: false
    switchDelay: 40 # 20 ticks = 1 second
    lists:
      index01:
        header:
          - '&6Welcome to Minecraft Server'
          - ''
        footer:
          - ''
          - '&6Use /discord join our discord'
        per-player: "%vault_rank% %player_name% %cl-version%"
      index02:
        header:
          - '&6Welcome to Minecraft Server'
          - ''
        footer:
          - ''
          - '&6Use /teamspeak join our teamspeak'
        per-player: "%vault_rank% %player_name% %cl-version%"        per-player: "%vault_rank% %player_name% %cl-version%"
  enabled: false
  WorldEnvironments:
    enabled: false
    allowHunger: false
    allowDamage: false
    allowPvp: false
    allowTp: true
    allowFly: true
    allowBlockBreak: false
    allowBlockPlace: false
    allowInteract: true
    disableNether: false
    disableEnd: false

  ChunkLoadingLimits:
    enabled: false
    interval: 20 # 20 Ticks = 1 Second
    maxChunks: 200