name: PowerExt_CommandPanel
version: '${project.version}'
main: me.overlight.powertools.commandpanel.PowerExt
depend: [ PowerToolS ]
authors: [ _OverLight_ ]
description: PowerToolS Extension - Connect panels to commands
